### ISSUE TITLE
Crash on latest version (1.13-1.20.1)

### ISSUE THREAD

**Issue by Drakoflame** [OopsOnlyDelta/redeco#12]
**Describe the bug**
The crash appears to involve an error when a wandering trader spawns in. The crash log says something about a "Soul Terrarium"

**To Reproduce**
Seemingly when a wandering trader is supposed to spawn containing soul terrarium loot

**Expected behavior**
not to crash :P

**Additional context**
No crashlog is printed, the game just locks up. Note, this is on a multiplayer server. appologies for the log dump, but this is the snippet that I caught when the crash happens

Couldn't parse element loot_tables:redeco:blocks/soul_terrarium
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'redeco:soul_terrarium'
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:145)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.GsonHelper.m_13874_(GsonHelper.java:145)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.GsonHelper.m_13909_(GsonHelper.java:153)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:55)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:40)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1214)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1319)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1290)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:471)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:192)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:189)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1214)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1319)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1290)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:294)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:291)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1214)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1319)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1261)
	at TRANSFORMER/forge@47.3.10/net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:871)
	at TRANSFORMER/forge@47.3.10/net.minecraftforge.common.ForgeHooks.lambda$getLootTableDeserializer$3(ForgeHooks.java:848)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:56)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootDataManager.m_278660_(LootDataManager.java:55)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Drakoflame** [comment]
Downgraded to version 1.12-1.20 and the crash still happens. removing the mod from the modpack to see if further issues persist or if it's resolved

**Comment by Drakoflame** [comment]
Seems like it's an unrelated issue causing the crash. I just happened to catch that error at the same time
